/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistaContent;

import SistemaContarVotos.ActaElectoral;
import SistemaContarVotos.GestionActas;
import SistemaContarVotos.GestionMesas;
import SistemaContarVotos.GestionPartidoPolitico;
import SistemaContarVotos.MesaElectoral;
import SistemaContarVotos.PartidoPolitico;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class ActasElectorales extends javax.swing.JPanel {

    private GestionMesas gestorMesas;
    private GestionActas gestorActas;

    /**
     * Creates new form Partidos
     */
    public ActasElectorales() {
        initComponents();
    }
    public ActasElectorales(GestionMesas gestorMesas, GestionActas gestorActas) {
    initComponents();
    this.gestorMesas = gestorMesas;
    this.gestorActas = gestorActas;

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        txtDigitarTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDigitarFecha = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtDigitarLugar = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtDigitarHora = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        txtDigitarActaUnico = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        combMesaElectoralActa = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtDigitarMiembro = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtDigitarNroRegistrados = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtDigitarEfectivos = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtResultadoCandidato = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtDigitarVotosBlanco = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtDigitarVotosNulo = new javax.swing.JTextField();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtDigitarObservacion = new javax.swing.JTextField();
        jSeparator20 = new javax.swing.JSeparator();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txtDigitarFirma = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        txtDigitarSello = new javax.swing.JTextField();
        btnRegistrarActa = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(550, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 34, 106, 10));

        txtDigitarTitulo.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarTitulo.setText("TItulo");
        txtDigitarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarTituloActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 6, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Titulo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 11, -1, -1));

        txtDigitarFecha.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarFecha.setText("Fecha");
        txtDigitarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 6, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 34, 64, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Lugar");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, -1, -1));

        txtDigitarLugar.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarLugar.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarLugar.setText("Lugar");
        txtDigitarLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarLugarActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 50, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 79, 106, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Hora");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        txtDigitarHora.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarHora.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarHora.setText("Hora");
        txtDigitarHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarHoraActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 64, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("N° Acta");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 11, -1, -1));

        txtDigitarActaUnico.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarActaUnico.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarActaUnico.setText("N°Acta");
        txtDigitarActaUnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarActaUnicoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarActaUnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 6, -1, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 34, 64, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, 539, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Mesa Electoral");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, -1, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 142, 72, 10));

        combMesaElectoralActa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(combMesaElectoralActa, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 114, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Miembro:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 203, -1, -1));

        txtDigitarMiembro.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarMiembro.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarMiembro.setText("Digitar ");
        txtDigitarMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarMiembroActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 198, -1, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 226, 64, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Votantes Registrados:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 119, -1, -1));

        txtDigitarNroRegistrados.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarNroRegistrados.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarNroRegistrados.setText("N°");
        txtDigitarNroRegistrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarNroRegistradosActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarNroRegistrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 114, -1, -1));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 142, 64, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Votantes Efectivos:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 159, -1, -1));

        txtDigitarEfectivos.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarEfectivos.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarEfectivos.setText("N°");
        txtDigitarEfectivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarEfectivosActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarEfectivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 154, -1, -1));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 182, 64, 10));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 242, 539, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Resultado por candidato:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        txtResultadoCandidato.setBackground(new java.awt.Color(255, 255, 255));
        txtResultadoCandidato.setForeground(new java.awt.Color(0, 0, 0));
        txtResultadoCandidato.setText("Digitar");
        txtResultadoCandidato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoCandidatoActionPerformed(evt);
            }
        });
        jPanel1.add(txtResultadoCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 64, 10));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Votos Blanco: ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        txtDigitarVotosBlanco.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarVotosBlanco.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarVotosBlanco.setText("Digitar ");
        txtDigitarVotosBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarVotosBlancoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarVotosBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));
        jPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 64, 10));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Votos Nulo: ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        txtDigitarVotosNulo.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarVotosNulo.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarVotosNulo.setText("Digitar ");
        txtDigitarVotosNulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarVotosNuloActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarVotosNulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));
        jPanel1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 64, 10));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Observacion:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 260, -1, -1));

        txtDigitarObservacion.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarObservacion.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarObservacion.setText("Digitar ");
        txtDigitarObservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarObservacionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 258, 175, -1));
        jPanel1.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 286, 175, 10));
        jPanel1.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 64, 10));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Firma:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        txtDigitarFirma.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarFirma.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarFirma.setText("Digitar");
        txtDigitarFirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarFirmaActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarFirma, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));
        jPanel1.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 64, 10));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Sello Oficial:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        txtDigitarSello.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarSello.setForeground(new java.awt.Color(0, 0, 0));
        txtDigitarSello.setText("Digitar");
        txtDigitarSello.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarSelloActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarSello, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        btnRegistrarActa.setBackground(new java.awt.Color(255, 0, 0));
        btnRegistrarActa.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btnRegistrarActa.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarActa.setText("Registrar Acta");
        btnRegistrarActa.setBorder(null);
        btnRegistrarActa.setBorderPainted(false);
        btnRegistrarActa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarActa, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 120, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDigitarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarTituloActionPerformed

    private void txtDigitarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarFechaActionPerformed

    private void txtDigitarLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarLugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarLugarActionPerformed

    private void txtDigitarHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarHoraActionPerformed

    private void txtDigitarActaUnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarActaUnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarActaUnicoActionPerformed

    private void txtDigitarMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarMiembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarMiembroActionPerformed

    private void txtDigitarNroRegistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarNroRegistradosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarNroRegistradosActionPerformed

    private void txtDigitarEfectivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarEfectivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarEfectivosActionPerformed

    private void txtResultadoCandidatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoCandidatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoCandidatoActionPerformed

    private void txtDigitarVotosBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarVotosBlancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarVotosBlancoActionPerformed

    private void txtDigitarVotosNuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarVotosNuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarVotosNuloActionPerformed

    private void txtDigitarObservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarObservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarObservacionActionPerformed

    private void txtDigitarFirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarFirmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarFirmaActionPerformed

    private void txtDigitarSelloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarSelloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarSelloActionPerformed

    private void btnRegistrarActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActaActionPerformed
        // TODO add your handling code here:
        try {
            String titulo = txtDigitarTitulo.getText().trim();
            String fecha = txtDigitarFecha.getText().trim();
            String hora = txtDigitarHora.getText().trim();
            String lugar = txtDigitarLugar.getText().trim();
            String idMesa = (String) combMesaElectoralActa.getSelectedItem();
            String miembros = txtDigitarMiembro.getText().trim();
            int totalVotantes = Integer.parseInt(txtDigitarNroRegistrados.getText().trim());
            int totalEfectivos = Integer.parseInt(txtDigitarEfectivos.getText().trim());
            int blancos = Integer.parseInt(txtDigitarVotosBlanco.getText().trim());
            int nulos = Integer.parseInt(txtDigitarVotosNulo.getText().trim());
            String observaciones = txtDigitarObservacion.getText().trim();
            String firmas = txtDigitarFirma.getText().trim();
            String sello = txtDigitarSello.getText().trim();
            String numeroActa = txtDigitarActaUnico.getText().trim();

            MesaElectoral mesaSeleccionada = null;
            for (MesaElectoral m : gestorMesas.getMesas()) {
                if (m != null && m.getIdMesa().equals(idMesa)) {
                    mesaSeleccionada = m;
                    break;
                }
            }

            if (mesaSeleccionada == null) {
                JOptionPane.showMessageDialog(this, "Mesa electoral no encontrada.");
                return;
            }

            ActaElectoral acta = new ActaElectoral(
                    numeroActa, titulo, hora, fecha, lugar, mesaSeleccionada,
                    totalVotantes, totalEfectivos, nulos, blancos,
                    firmas, sello, observaciones, 0
            );

            gestorActas.registrarActa(acta);

            JOptionPane.showMessageDialog(this, "Acta registrada exitosamente.");
            limpiarCampos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Verifica que los campos numéricos tengan valores válidos.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al registrar el acta: " + e.getMessage());
        }


    }//GEN-LAST:event_btnRegistrarActaActionPerformed

    private void limpiarCampos() {
        txtDigitarTitulo.setText("");
        txtDigitarFecha.setText("");
        txtDigitarHora.setText("");
        txtDigitarLugar.setText("");
        txtDigitarMiembro.setText("");
        txtDigitarNroRegistrados.setText("");
        txtDigitarEfectivos.setText("");
        txtDigitarVotosBlanco.setText("");
        txtDigitarVotosNulo.setText("");
        txtDigitarObservacion.setText("");
        txtDigitarFirma.setText("");
        txtDigitarSello.setText("");
        txtDigitarActaUnico.setText("");
        combMesaElectoralActa.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnRegistrarActa;
    private javax.swing.JComboBox<String> combMesaElectoralActa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtDigitarActaUnico;
    private javax.swing.JTextField txtDigitarEfectivos;
    private javax.swing.JTextField txtDigitarFecha;
    private javax.swing.JTextField txtDigitarFirma;
    private javax.swing.JTextField txtDigitarHora;
    private javax.swing.JTextField txtDigitarLugar;
    private javax.swing.JTextField txtDigitarMiembro;
    private javax.swing.JTextField txtDigitarNroRegistrados;
    private javax.swing.JTextField txtDigitarObservacion;
    private javax.swing.JTextField txtDigitarSello;
    private javax.swing.JTextField txtDigitarTitulo;
    private javax.swing.JTextField txtDigitarVotosBlanco;
    private javax.swing.JTextField txtDigitarVotosNulo;
    private javax.swing.JTextField txtResultadoCandidato;
    // End of variables declaration//GEN-END:variables
}
