/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistaContent;

import SistemaContarVotos.Candidato;
import SistemaContarVotos.Eleccion;
import SistemaContarVotos.GestionCandidatos;
import SistemaContarVotos.GestionElecciones;
import SistemaContarVotos.GestionPartidoPolitico;
import SistemaContarVotos.PartidoPolitico;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Elecciones extends javax.swing.JPanel {

    private GestionCandidatos gestorCandidatos;
    private GestionElecciones gestorElecciones;

    /**
     * Creates new form Partidos
     */
    public Elecciones(GestionCandidatos gestorCandidatos, GestionElecciones gestorElecciones) {
        initComponents();
        this.gestorCandidatos = gestorCandidatos;
        this.gestorElecciones = gestorElecciones;
        cargarCandidatosDisponibles();
    }

    private void cargarCandidatosDisponibles() {
        DefaultListModel<String> modeloLista = new DefaultListModel<>();

        Candidato[] lista = gestorCandidatos.getCandidatos();

        for (Candidato c : lista) {
            modeloLista.addElement(c.getNombres() + " " + c.getApellidos());
        }

        listEleccion.setModel(modeloLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEleccion = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEleccion = new javax.swing.JList<>();
        txtFecha = new javax.swing.JLabel();
        txtDiaMesAnio = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtregistrareleccion = new javax.swing.JLabel();
        txtDigitarEleccion = new javax.swing.JTextField();
        txtTipoELeccion = new javax.swing.JLabel();
        txtCandidatosAsociados = new javax.swing.JLabel();
        txtDigitarCandidatos = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(550, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);

        tablaEleccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane2.setViewportView(tablaEleccion);

        listEleccion.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listEleccion);

        txtFecha.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setText("Fecha");

        txtDiaMesAnio.setBackground(new java.awt.Color(255, 255, 255));
        txtDiaMesAnio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDiaMesAnio.setForeground(new java.awt.Color(204, 204, 204));
        txtDiaMesAnio.setText("DD/MM/AA");
        txtDiaMesAnio.setBorder(null);
        txtDiaMesAnio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDiaMesAnioMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDiaMesAnioMousePressed(evt);
            }
        });
        txtDiaMesAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaMesAnioActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(255, 0, 51));
        btnAgregar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtregistrareleccion.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        txtregistrareleccion.setForeground(new java.awt.Color(0, 0, 0));
        txtregistrareleccion.setText("REGISTRAR ELECCION");

        txtDigitarEleccion.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarEleccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDigitarEleccion.setForeground(new java.awt.Color(204, 204, 204));
        txtDigitarEleccion.setText("Digite");
        txtDigitarEleccion.setBorder(null);
        txtDigitarEleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDigitarEleccionMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDigitarEleccionMousePressed(evt);
            }
        });
        txtDigitarEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarEleccionActionPerformed(evt);
            }
        });

        txtTipoELeccion.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtTipoELeccion.setForeground(new java.awt.Color(0, 0, 0));
        txtTipoELeccion.setText("TIipo de Eleccion");

        txtCandidatosAsociados.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtCandidatosAsociados.setForeground(new java.awt.Color(0, 0, 0));
        txtCandidatosAsociados.setText("Candidatos Asociados");

        txtDigitarCandidatos.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarCandidatos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDigitarCandidatos.setForeground(new java.awt.Color(204, 204, 204));
        txtDigitarCandidatos.setText("Digite Candidatos");
        txtDigitarCandidatos.setBorder(null);
        txtDigitarCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDigitarCandidatosMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDigitarCandidatosMousePressed(evt);
            }
        });
        txtDigitarCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarCandidatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtregistrareleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha)
                    .addComponent(txtDiaMesAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoELeccion)
                    .addComponent(txtDigitarEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCandidatosAsociados)
                    .addComponent(txtDigitarCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtregistrareleccion)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFecha)
                        .addGap(6, 6, 6)
                        .addComponent(txtDiaMesAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtTipoELeccion)
                        .addGap(12, 12, 12)
                        .addComponent(txtDigitarEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtCandidatosAsociados)
                        .addGap(12, 12, 12)
                        .addComponent(txtDigitarCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDigitarCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarCandidatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarCandidatosActionPerformed

    private void txtDigitarCandidatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDigitarCandidatosMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarCandidatosMousePressed

    private void txtDigitarCandidatosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDigitarCandidatosMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarCandidatosMouseEntered

    private void txtDigitarEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarEleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarEleccionActionPerformed

    private void txtDigitarEleccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDigitarEleccionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarEleccionMousePressed

    private void txtDigitarEleccionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDigitarEleccionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarEleccionMouseEntered

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String fecha = txtDiaMesAnio.getText().trim();
        String eleccion = txtDigitarEleccion.getText().trim();

        if (fecha.isEmpty() || eleccion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }

        Eleccion nuevo = new Eleccion(eleccion, fecha, 10);
        List<String> seleccionados = listEleccion.getSelectedValuesList();
        if (seleccionados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar al menos un candidato.");
            return;
        }
        List<Candidato> candidatosAsociados = new ArrayList<>();
        for (String nombreCompleto : seleccionados) {
            for (Candidato c : gestorCandidatos.getCandidatos()) {
                String nombreCandidato = c.getNombres() + " " + c.getApellidos();
                if (nombreCandidato.equalsIgnoreCase(nombreCompleto)) {
                    candidatosAsociados.add(c);
                    break;
                }
            }
        }
        Eleccion nueva = new Eleccion(eleccion, fecha, 10);

        for (Candidato c : candidatosAsociados) {
            nuevo.agregarCandidato(c);
        }

        boolean registrado = gestorElecciones.agregarEleccion(nueva);

        if (registrado) {
            DefaultTableModel modelo = (DefaultTableModel) tablaEleccion.getModel();
            modelo.addRow(new Object[]{fecha, seleccionados.size() + " candidatos"});
            txtDiaMesAnio.setText("");
            txtDigitarEleccion.setText("");
            listEleccion.clearSelection();

        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar el partido. Capacidad máxima alcanzada.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tablaEleccion.getSelectedRow();

        if (filaSeleccionada >= 0) {
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Estás seguro de eliminar el partido seleccionado?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {

                DefaultTableModel modelo = (DefaultTableModel) tablaEleccion.getModel();
                modelo.removeRow(filaSeleccionada);

                boolean eliminado = gestorElecciones.eliminarEleccion(filaSeleccionada);

                if (!eliminado) {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar del arreglo.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtDiaMesAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaMesAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaMesAnioActionPerformed

    private void txtDiaMesAnioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiaMesAnioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaMesAnioMousePressed

    private void txtDiaMesAnioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDiaMesAnioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaMesAnioMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JList<String> listEleccion;
    private javax.swing.JTable tablaEleccion;
    private javax.swing.JLabel txtCandidatosAsociados;
    private javax.swing.JTextField txtDiaMesAnio;
    private javax.swing.JTextField txtDigitarCandidatos;
    private javax.swing.JTextField txtDigitarEleccion;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtTipoELeccion;
    private javax.swing.JLabel txtregistrareleccion;
    // End of variables declaration//GEN-END:variables
}
