package vistaContent;

import SistemaContarVotos.Candidato;
import SistemaContarVotos.GeneradorInformes;
import SistemaContarVotos.GeneradorInformes.InformePorMesa;
import SistemaContarVotos.GestionActas;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Informes extends javax.swing.JPanel {

    private GestionActas gestorActas;
    private DefaultTableModel modelo;

    /**
     * Creates new form Partidos
     */
    public Informes(GestionActas gestorActas) {
        initComponents();
        this.gestorActas = gestorActas;

        modelo = new DefaultTableModel(
                new String[]{"Mesa", "Lugar", "Total Votantes", "Votos Emitidos", "Nulos", "Blancos", "Resultados"}, 0
        );
        tablaInforme.setModel(modelo);
        cargarElecciones();
    }

    private void cargarElecciones() {
        String[] elecciones = gestorActas.getNombresElecciones();
        jComboBox1.removeAllItems();
        for (int i = 0; i < elecciones.length; i++) {
            if (elecciones[i] != null) {
                jComboBox1.addItem(elecciones[i]);
            }
        }

        jComboBox1.addActionListener(e -> cargarMesasPorEleccion());
    }

    private void cargarMesasPorEleccion() {
        String eleccionSeleccionada = (String) jComboBox1.getSelectedItem();
        if (eleccionSeleccionada == null) {
            return;
        }

        String[] mesas = gestorActas.getMesasPorEleccion(eleccionSeleccionada);
        jComboBox2.removeAllItems();
        for (int i = 0; i < mesas.length; i++) {
            if (mesas[i] != null) {
                jComboBox2.addItem(mesas[i]);
            }
        }

        jComboBox2.addActionListener(e -> cargarInformePorMesa());
    }

    private void cargarInformePorMesa() {
        String mesaSeleccionada = (String) jComboBox2.getSelectedItem();
        if (mesaSeleccionada == null) {
            return;
        }

        // Limpia tabla
        modelo.setRowCount(0);

        InformePorMesa[] informes = GeneradorInformes.generarInformeMesas(gestorActas);
        for (int i = 0; i < informes.length; i++) {
            InformePorMesa informe = informes[i];
            if (informe.getCodigoMesa().equalsIgnoreCase(mesaSeleccionada)) {
                String resumen = generarResumenResultados(
                        informe.getCandidatos(),
                        informe.getVotosPorCandidato(),
                        informe.getNumCandidatos()
                );

                Object[] fila = {
                    informe.getCodigoMesa(),
                    informe.getLugar(),
                    informe.getTotalVotantes(),
                    informe.getVotosEmitidos(),
                    informe.getVotosNulos(),
                    informe.getVotosBlancos(),
                    resumen
                };
                modelo.addRow(fila);
                break;
            }
        }
    }

    private String generarResumenResultados(Candidato[] candidatos, int[] votos, int total) {
        String resumen = "";
        for (int i = 0; i < total; i++) {
            Candidato c = candidatos[i];
            resumen += c.getNombres() + " " + c.getApellidos() + " = " + votos[i];
            if (i < total - 1) {
                resumen += ", ";
            }
        }
        return resumen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombredelPartidoPolitico = new javax.swing.JLabel();
        txtregistrarunpartido = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtNombredelPartidoPolitico1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInforme = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(550, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);

        txtNombredelPartidoPolitico.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtNombredelPartidoPolitico.setForeground(new java.awt.Color(0, 0, 0));
        txtNombredelPartidoPolitico.setText("Seleccionar Eleccion: ");

        txtregistrarunpartido.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        txtregistrarunpartido.setForeground(new java.awt.Color(0, 0, 0));
        txtregistrarunpartido.setText("INFORME");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtNombredelPartidoPolitico1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtNombredelPartidoPolitico1.setForeground(new java.awt.Color(0, 0, 0));
        txtNombredelPartidoPolitico1.setText("Seleccionar Mesa Electoral: ");

        tablaInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mesa", "Lugar", "Total Votantes", "Votos Emitidos", "Nulos", "Blancos", "Resultados"
            }
        ));
        jScrollPane1.setViewportView(tablaInforme);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtregistrarunpartido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombredelPartidoPolitico1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator5)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombredelPartidoPolitico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator1)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombredelPartidoPolitico)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombredelPartidoPolitico1)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(txtregistrarunpartido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable tablaInforme;
    private javax.swing.JLabel txtNombredelPartidoPolitico;
    private javax.swing.JLabel txtNombredelPartidoPolitico1;
    private javax.swing.JLabel txtregistrarunpartido;
    // End of variables declaration//GEN-END:variables
}
