/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistaContent;

import SistemaContarVotos.GestionMesas;
import SistemaContarVotos.GestionPartidoPolitico;
import SistemaContarVotos.MesaElectoral;
import SistemaContarVotos.MiembroMesa;
import SistemaContarVotos.PartidoPolitico;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */

public class MiembrosMesa extends javax.swing.JPanel {

    private GestionMesas gestorMesas;
    private DefaultTableModel modelo;
    private MesaElectoral mesaSeleccionada;
    /**
     * Creates new form Partidos
     */
    public MiembrosMesa(GestionMesas gestorMesas) {
        initComponents();
        this.gestorMesas = gestorMesas;

        modelo = new DefaultTableModel(new Object[]{"Nombre", "Apellido", "Tipo", "Mesa"}, 0);
        tablaMiembros.setModel(modelo);

        comboTipoMiembro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"presidente", "secretario", "vocal"}));

        cargarMesas();
    }
    private void cargarMesas() {
    comboMesaElectoral.removeAllItems();
    for (MesaElectoral m : gestorMesas.getMesas()) {
        if (m != null) {
            comboMesaElectoral.addItem(m.getIdMesa());
        }
    }
}
    public MiembrosMesa(GestionMesas gestorMesas, MesaElectoral mesaSeleccionada) {
        initComponents();
        this.gestorMesas = gestorMesas;
        this.mesaSeleccionada = mesaSeleccionada;
        modelo = new DefaultTableModel(new Object[]{"Nombre", "Apellido", "Tipo", "Mesa"}, 0);
    tablaMiembros.setModel(modelo);

    comboTipoMiembro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"presidente", "secretario", "vocal"}));
    comboMesaElectoral.removeAllItems();
    comboMesaElectoral.addItem(mesaSeleccionada.getIdMesa());
    comboMesaElectoral.setSelectedIndex(0);
    
    cargarMiembrosDeMesaSeleccionada();

    }
    
    private void cargarMiembrosDeMesaSeleccionada() {
    if (mesaSeleccionada != null) {
        modelo.setRowCount(0); // Limpiar la tabla antes de llenar

        if (mesaSeleccionada.getPresidente() != null && !mesaSeleccionada.getPresidente().getNombres().isEmpty()) {
            MiembroMesa m = mesaSeleccionada.getPresidente();
            modelo.addRow(new Object[]{m.getNombres(), m.getApellidos(), "presidente", mesaSeleccionada.getIdMesa()});
        }
        if (mesaSeleccionada.getSecretario() != null && !mesaSeleccionada.getSecretario().getNombres().isEmpty()) {
            MiembroMesa m = mesaSeleccionada.getSecretario();
            modelo.addRow(new Object[]{m.getNombres(), m.getApellidos(), "secretario", mesaSeleccionada.getIdMesa()});
        }
        if (mesaSeleccionada.getVocal() != null && !mesaSeleccionada.getVocal().getNombres().isEmpty()) {
            MiembroMesa m = mesaSeleccionada.getVocal();
            modelo.addRow(new Object[]{m.getNombres(), m.getApellidos(), "vocal", mesaSeleccionada.getIdMesa()});
        }
    }
}

    
    
    private void limpiarCampos() {
    txtDigitarNombreMiembro.setText("");
    txtDigitarApellido.setText("");
    comboTipoMiembro.setSelectedIndex(0);
    comboMesaElectoral.setSelectedIndex(0);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMiembros = new javax.swing.JTable();
        txtNombreMiembro = new javax.swing.JLabel();
        txtDigitarNombreMiembro = new javax.swing.JTextField();
        txtMesaElectoral = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtregistrarunpartido = new javax.swing.JLabel();
        txtDigitarApellido = new javax.swing.JTextField();
        txtApellido = new javax.swing.JLabel();
        txtRepresentantelegal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        comboTipoMiembro = new javax.swing.JComboBox<>();
        comboMesaElectoral = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(550, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMiembros.setBackground(new java.awt.Color(255, 255, 255));
        tablaMiembros.setForeground(new java.awt.Color(0, 0, 0));
        tablaMiembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Tipo", "Mesa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaMiembros);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 62, 313, 224));

        txtNombreMiembro.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtNombreMiembro.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreMiembro.setText("Nombre ");
        jPanel1.add(txtNombreMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, -1, -1));

        txtDigitarNombreMiembro.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarNombreMiembro.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDigitarNombreMiembro.setForeground(new java.awt.Color(204, 204, 204));
        txtDigitarNombreMiembro.setText("Nombre ");
        txtDigitarNombreMiembro.setBorder(null);
        txtDigitarNombreMiembro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDigitarNombreMiembroMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDigitarNombreMiembroMousePressed(evt);
            }
        });
        txtDigitarNombreMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarNombreMiembroActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarNombreMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, 184, 20));

        txtMesaElectoral.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtMesaElectoral.setForeground(new java.awt.Color(0, 0, 0));
        txtMesaElectoral.setText(" Mesa Electoral");
        jPanel1.add(txtMesaElectoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 309, 85, 23));

        btnAgregar.setBackground(new java.awt.Color(255, 0, 51));
        btnAgregar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 309, 85, 23));

        txtregistrarunpartido.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        txtregistrarunpartido.setForeground(new java.awt.Color(0, 0, 0));
        txtregistrarunpartido.setText("REGISTRAR MIEMBROS DE MESA");
        jPanel1.add(txtregistrarunpartido, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 27, -1, -1));

        txtDigitarApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarApellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDigitarApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtDigitarApellido.setText("Digitar apellido");
        txtDigitarApellido.setBorder(null);
        txtDigitarApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDigitarApellidoMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDigitarApellidoMousePressed(evt);
            }
        });
        txtDigitarApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDigitarApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 184, 20));

        txtApellido.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setText("Apellido");
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 147, -1, -1));

        txtRepresentantelegal.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtRepresentantelegal.setForeground(new java.awt.Color(0, 0, 0));
        txtRepresentantelegal.setText("Tipo");
        jPanel1.add(txtRepresentantelegal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 212, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 131, 184, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 196, 184, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 264, 184, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 184, 10));

        comboTipoMiembro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboTipoMiembro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        comboMesaElectoral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboMesaElectoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDigitarApellidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDigitarApellidoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarApellidoMouseEntered

    private void txtDigitarApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDigitarApellidoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarApellidoMousePressed

    private void txtDigitarApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarApellidoActionPerformed

    private void txtDigitarNombreMiembroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDigitarNombreMiembroMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarNombreMiembroMouseEntered

    private void txtDigitarNombreMiembroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDigitarNombreMiembroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarNombreMiembroMousePressed

    private void txtDigitarNombreMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarNombreMiembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarNombreMiembroActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        String nombre = txtDigitarNombreMiembro.getText().trim();
        String apellido = txtDigitarApellido.getText().trim();
        String tipo = ((String) comboTipoMiembro.getSelectedItem()).toLowerCase();
        String idMesa = (String) comboMesaElectoral.getSelectedItem();

        if (nombre.isEmpty() || apellido.isEmpty() || tipo == null || idMesa == null) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos.");
            return;
        }

        MiembroMesa nuevoMiembro = new MiembroMesa(nombre, apellido, tipo);

        // Buscar la mesa y asignar
        for (MesaElectoral mesa : gestorMesas.getMesas()) {
            if (mesa != null && mesa.getIdMesa().equals(idMesa)) {
                boolean asignado = mesa.asignarMiembro(nuevoMiembro);
                if (asignado) {
                    modelo.addRow(new Object[]{nombre, apellido, tipo, idMesa});
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Tipo de miembro inválido.");
                }
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Mesa no encontrada.");
    }//GEN-LAST:event_btnAgregarActionPerformed




    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tablaMiembros.getSelectedRow();

        if (filaSeleccionada >= 0) {
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Estás seguro de eliminar el miembro seleccionado?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                String tipo = (String) tablaMiembros.getValueAt(filaSeleccionada, 2); // columna tipo
                String idMesa = (String) tablaMiembros.getValueAt(filaSeleccionada, 3); // columna mesa

                // Buscar la mesa
                for (MesaElectoral mesa : gestorMesas.getMesas()) {
                    if (mesa != null && mesa.getIdMesa().equals(idMesa)) {
                        // Eliminar el miembro correspondiente
                        switch (tipo.toLowerCase()) {
                            case "presidente":
                                mesa.asignarMiembro(new MiembroMesa("", "", "presidente")); // limpia presidente
                                break;
                            case "secretario":
                                mesa.asignarMiembro(new MiembroMesa("", "", "secretario")); // limpia secretario
                                break;
                            case "vocal":
                                mesa.asignarMiembro(new MiembroMesa("", "", "vocal")); // limpia vocal
                                break;
                        }
                        break;
                    }
                }

                // Quitar de la tabla
                DefaultTableModel modelo = (DefaultTableModel) tablaMiembros.getModel();
                modelo.removeRow(filaSeleccionada);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.");
        }

    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> comboMesaElectoral;
    private javax.swing.JComboBox<String> comboTipoMiembro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tablaMiembros;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JTextField txtDigitarApellido;
    private javax.swing.JTextField txtDigitarNombreMiembro;
    private javax.swing.JLabel txtMesaElectoral;
    private javax.swing.JLabel txtNombreMiembro;
    private javax.swing.JLabel txtRepresentantelegal;
    private javax.swing.JLabel txtregistrarunpartido;
    // End of variables declaration//GEN-END:variables
}
