package vistaContent;

import SistemaContarVotos.GestionPartidoPolitico;
import SistemaContarVotos.PartidoPolitico;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Partidos extends javax.swing.JPanel {

    private GestionPartidoPolitico gestor = new GestionPartidoPolitico(100);

    /**
     * Creates new form Partidos
     */
    public Partidos(GestionPartidoPolitico gestorPartidos) {
        this.gestor = gestorPartidos;
        initComponents();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(new String[]{"Nombre", "Sigla", "Representante", "Símbolo"});
        tablaPartidos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPartidos = new javax.swing.JTable();
        txtNombredelPartidoPolitico = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txtlogo = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtregistrarunpartido = new javax.swing.JLabel();
        txtDigitarsiglas = new javax.swing.JTextField();
        txtSigla = new javax.swing.JLabel();
        txtRepresentantelegal = new javax.swing.JLabel();
        txtnombredelrepresentante = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(550, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);

        tablaPartidos.setBackground(new java.awt.Color(255, 255, 255));
        tablaPartidos.setForeground(new java.awt.Color(0, 0, 0));
        tablaPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Sigla", "Representate", "Simbolo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaPartidos);

        txtNombredelPartidoPolitico.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtNombredelPartidoPolitico.setForeground(new java.awt.Color(0, 0, 0));
        txtNombredelPartidoPolitico.setText("Nombre del partido politico");

        txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(204, 204, 204));
        txt_nombre.setText("Nombre ");
        txt_nombre.setBorder(null);
        txt_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_nombreMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_nombreMousePressed(evt);
            }
        });
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        txtlogo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtlogo.setForeground(new java.awt.Color(0, 0, 0));
        txtlogo.setText("Logo /  Simbolo distintivo");

        txtdescripcion.setBackground(new java.awt.Color(255, 255, 255));
        txtdescripcion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtdescripcion.setForeground(new java.awt.Color(204, 204, 204));
        txtdescripcion.setText("Descripción del logo");
        txtdescripcion.setBorder(null);
        txtdescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtdescripcionMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtdescripcionMousePressed(evt);
            }
        });
        txtdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcionActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(255, 0, 51));
        btnAgregar.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.setBorderPainted(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtregistrarunpartido.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        txtregistrarunpartido.setForeground(new java.awt.Color(0, 0, 0));
        txtregistrarunpartido.setText("REGISTRAR UN PARTIDO POLITICO");

        txtDigitarsiglas.setBackground(new java.awt.Color(255, 255, 255));
        txtDigitarsiglas.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDigitarsiglas.setForeground(new java.awt.Color(204, 204, 204));
        txtDigitarsiglas.setText("Digite las siglas");
        txtDigitarsiglas.setBorder(null);
        txtDigitarsiglas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDigitarsiglasMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDigitarsiglasMousePressed(evt);
            }
        });
        txtDigitarsiglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDigitarsiglasActionPerformed(evt);
            }
        });

        txtSigla.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtSigla.setForeground(new java.awt.Color(0, 0, 0));
        txtSigla.setText("Sigla");

        txtRepresentantelegal.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtRepresentantelegal.setForeground(new java.awt.Color(0, 0, 0));
        txtRepresentantelegal.setText("Representante legal");

        txtnombredelrepresentante.setBackground(new java.awt.Color(255, 255, 255));
        txtnombredelrepresentante.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtnombredelrepresentante.setForeground(new java.awt.Color(204, 204, 204));
        txtnombredelrepresentante.setText("Nombre del representante legal");
        txtnombredelrepresentante.setBorder(null);
        txtnombredelrepresentante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtnombredelrepresentanteMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnombredelrepresentanteMousePressed(evt);
            }
        });
        txtnombredelrepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombredelrepresentanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtregistrarunpartido, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlogo))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 52, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSigla)
                    .addComponent(txtRepresentantelegal)
                    .addComponent(txtNombredelPartidoPolitico)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtdescripcion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addComponent(txtnombredelrepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDigitarsiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtregistrarunpartido)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtNombredelPartidoPolitico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSigla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDigitarsiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRepresentantelegal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnombredelrepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlogo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDigitarsiglasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDigitarsiglasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarsiglasMouseEntered

    private void txtDigitarsiglasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDigitarsiglasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarsiglasMousePressed

    private void txtDigitarsiglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigitarsiglasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigitarsiglasActionPerformed

    private void txt_nombreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombreMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreMouseEntered

    private void txt_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreMousePressed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txtnombredelrepresentanteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombredelrepresentanteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombredelrepresentanteMouseEntered

    private void txtnombredelrepresentanteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombredelrepresentanteMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombredelrepresentanteMousePressed

    private void txtnombredelrepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombredelrepresentanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombredelrepresentanteActionPerformed

    private void txtdescripcionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdescripcionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcionMouseEntered

    private void txtdescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdescripcionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcionMousePressed

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcionActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = txt_nombre.getText().trim();
        String sigla = txtDigitarsiglas.getText().trim();
        String representante = txtnombredelrepresentante.getText().trim();
        String simbolo = txtdescripcion.getText().trim();

        if (nombre.trim().isEmpty() || sigla.trim().isEmpty() || representante.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return;
        }

        PartidoPolitico nuevo = new PartidoPolitico(nombre, sigla, representante, simbolo);
        boolean registrado = gestor.agregarPartido(nuevo);

        if (registrado) {
            DefaultTableModel modelo = (DefaultTableModel) tablaPartidos.getModel();
            modelo.addRow(new Object[]{nombre, sigla, representante, simbolo});
            txt_nombre.setText("");
            txtDigitarsiglas.setText("");
            txtnombredelrepresentante.setText("");
            txtdescripcion.setText("");

        } else {
            JOptionPane.showMessageDialog(this, "No se pudo registrar el partido. Capacidad máxima alcanzada.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tablaPartidos.getSelectedRow();

        if (filaSeleccionada >= 0) {
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Estás seguro de eliminar el partido seleccionado?",
                    "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {

                DefaultTableModel modelo = (DefaultTableModel) tablaPartidos.getModel();
                modelo.removeRow(filaSeleccionada);

                boolean eliminado = gestor.eliminarPartido(filaSeleccionada);

                if (!eliminado) {
                    JOptionPane.showMessageDialog(this, "No se pudo eliminar del arreglo.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tablaPartidos;
    private javax.swing.JTextField txtDigitarsiglas;
    private javax.swing.JLabel txtNombredelPartidoPolitico;
    private javax.swing.JLabel txtRepresentantelegal;
    private javax.swing.JLabel txtSigla;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JLabel txtlogo;
    private javax.swing.JTextField txtnombredelrepresentante;
    private javax.swing.JLabel txtregistrarunpartido;
    // End of variables declaration//GEN-END:variables
}
