/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_sistema;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {
    
    int xMouse, yMouse;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo_blanco = new javax.swing.JPanel();
        img_vote = new javax.swing.JLabel();
        text_iniciarsesion = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JLabel();
        txt_nombredeusuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_contrasena = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        moverpartesuperior = new javax.swing.JPanel();
        jpanelParteSuperior = new javax.swing.JPanel();
        btn_Xdesalir = new javax.swing.JLabel();
        btn_ingresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        fondo_blanco.setBackground(new java.awt.Color(255, 255, 255));
        fondo_blanco.setForeground(new java.awt.Color(204, 204, 204));
        fondo_blanco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fondo_blanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img_vote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_login/vote_260x500.jpg"))); // NOI18N
        img_vote.setText("jLabel2");
        fondo_blanco.add(img_vote, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 260, 500));

        text_iniciarsesion.setBackground(new java.awt.Color(0, 0, 0));
        text_iniciarsesion.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        text_iniciarsesion.setForeground(new java.awt.Color(0, 0, 0));
        text_iniciarsesion.setText("INICIAR SESION");
        fondo_blanco.add(text_iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txt_usuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(0, 0, 0));
        txt_usuario.setText("USUARIO");
        fondo_blanco.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txt_nombredeusuario.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombredeusuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_nombredeusuario.setForeground(new java.awt.Color(204, 204, 204));
        txt_nombredeusuario.setText("Ingrese su ID");
        txt_nombredeusuario.setBorder(null);
        txt_nombredeusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_nombredeusuarioMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_nombredeusuarioMousePressed(evt);
            }
        });
        txt_nombredeusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombredeusuarioActionPerformed(evt);
            }
        });
        fondo_blanco.add(txt_nombredeusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 260, 20));
        fondo_blanco.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 310, 10));

        txt_contrasena.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txt_contrasena.setForeground(new java.awt.Color(0, 0, 0));
        txt_contrasena.setText("CONTRASEÑA");
        fondo_blanco.add(txt_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        fondo_blanco.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 310, 10));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("********");
        jPasswordField1.setBorder(null);
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField1MousePressed(evt);
            }
        });
        fondo_blanco.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        moverpartesuperior.setBackground(new java.awt.Color(255, 255, 255));
        moverpartesuperior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moverpartesuperiorMouseDragged(evt);
            }
        });
        moverpartesuperior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moverpartesuperiorMousePressed(evt);
            }
        });

        jpanelParteSuperior.setBackground(new java.awt.Color(255, 255, 255));

        btn_Xdesalir.setBackground(new java.awt.Color(255, 255, 255));
        btn_Xdesalir.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        btn_Xdesalir.setForeground(new java.awt.Color(0, 0, 0));
        btn_Xdesalir.setText("X");
        btn_Xdesalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Xdesalir.setPreferredSize(new java.awt.Dimension(40, 40));
        btn_Xdesalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XdesalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_XdesalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_XdesalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpanelParteSuperiorLayout = new javax.swing.GroupLayout(jpanelParteSuperior);
        jpanelParteSuperior.setLayout(jpanelParteSuperiorLayout);
        jpanelParteSuperiorLayout.setHorizontalGroup(
            jpanelParteSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelParteSuperiorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_Xdesalir, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jpanelParteSuperiorLayout.setVerticalGroup(
            jpanelParteSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelParteSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Xdesalir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout moverpartesuperiorLayout = new javax.swing.GroupLayout(moverpartesuperior);
        moverpartesuperior.setLayout(moverpartesuperiorLayout);
        moverpartesuperiorLayout.setHorizontalGroup(
            moverpartesuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moverpartesuperiorLayout.createSequentialGroup()
                .addComponent(jpanelParteSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 754, Short.MAX_VALUE))
        );
        moverpartesuperiorLayout.setVerticalGroup(
            moverpartesuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moverpartesuperiorLayout.createSequentialGroup()
                .addComponent(jpanelParteSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        fondo_blanco.add(moverpartesuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        btn_ingresar.setBackground(new java.awt.Color(240, 0, 11));
        btn_ingresar.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        btn_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingresar.setText("INGRESAR");
        btn_ingresar.setBorder(null);
        btn_ingresar.setBorderPainted(false);
        btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        fondo_blanco.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo_blanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo_blanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombredeusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombredeusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombredeusuarioActionPerformed

    private void moverpartesuperiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverpartesuperiorMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_moverpartesuperiorMousePressed

    private void moverpartesuperiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moverpartesuperiorMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_moverpartesuperiorMouseDragged

    private void btn_XdesalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XdesalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_XdesalirMouseClicked

    private void btn_XdesalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XdesalirMouseEntered
        // TODO add your handling code here:
        jpanelParteSuperior.setBackground(Color.red);
        btn_Xdesalir.setForeground(Color.white);
    }//GEN-LAST:event_btn_XdesalirMouseEntered

    private void btn_XdesalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XdesalirMouseExited
        // TODO add your handling code here:
        jpanelParteSuperior.setBackground(Color.white);
        btn_Xdesalir.setForeground(Color.black);

    }//GEN-LAST:event_btn_XdesalirMouseExited

    private void txt_nombredeusuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombredeusuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombredeusuarioMouseEntered

    private void txt_nombredeusuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombredeusuarioMousePressed
        // TODO add your handling code here:
        if (txt_nombredeusuario.getText().equals("Ingrese su ID")){
            txt_nombredeusuario.setText("");
            txt_nombredeusuario.setForeground(Color.black);
        }
        if(String.valueOf(jPasswordField1.getPassword()).isEmpty()){
            jPasswordField1.setText("********");
            jPasswordField1.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_nombredeusuarioMousePressed

    private void jPasswordField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MousePressed
        // TODO add your handling code here:
        if (String.valueOf(jPasswordField1.getPassword()).equals("********")){
            jPasswordField1.setText("");
            jPasswordField1.setForeground(Color.black); 
        }
        if(txt_nombredeusuario.getText().isEmpty()){
            txt_nombredeusuario.setText("Ingrese su ID");
            txt_nombredeusuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_jPasswordField1MousePressed

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        
        String clave = new String(jPasswordField1.getPassword());
        
        if(clave.equals("1234")){
        Principal p1 = new Principal();
        p1.setVisible(true);
        this.dispose();
        }else{
            JOptionPane.showConfirmDialog(this, "Clave incorrecta");
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_Xdesalir;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JPanel fondo_blanco;
    private javax.swing.JLabel img_vote;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpanelParteSuperior;
    private javax.swing.JPanel moverpartesuperior;
    private javax.swing.JLabel text_iniciarsesion;
    private javax.swing.JLabel txt_contrasena;
    private javax.swing.JTextField txt_nombredeusuario;
    private javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
