/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login_sistema;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {
    
    int xMouse, yMouse;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo_blanco = new javax.swing.JPanel();
        img_vote = new javax.swing.JLabel();
        text_iniciarsesion = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JLabel();
        txt_nombredeusuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txt_contrasena = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        panel_ingresar = new javax.swing.JPanel();
        txt_ingresar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        fondo_blanco.setBackground(new java.awt.Color(255, 255, 255));
        fondo_blanco.setForeground(new java.awt.Color(204, 204, 204));
        fondo_blanco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fondo_blanco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img_vote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen_login/vote_260x500.jpg"))); // NOI18N
        img_vote.setText("jLabel2");
        fondo_blanco.add(img_vote, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 260, 500));

        text_iniciarsesion.setBackground(new java.awt.Color(0, 0, 0));
        text_iniciarsesion.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        text_iniciarsesion.setForeground(new java.awt.Color(0, 0, 0));
        text_iniciarsesion.setText("INICIAR SESION");
        fondo_blanco.add(text_iniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txt_usuario.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(0, 0, 0));
        txt_usuario.setText("USUARIO");
        fondo_blanco.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txt_nombredeusuario.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombredeusuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_nombredeusuario.setForeground(new java.awt.Color(204, 204, 204));
        txt_nombredeusuario.setText("Ingrese su ID");
        txt_nombredeusuario.setBorder(null);
        txt_nombredeusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombredeusuarioActionPerformed(evt);
            }
        });
        fondo_blanco.add(txt_nombredeusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 260, 20));
        fondo_blanco.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 310, 10));

        txt_contrasena.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txt_contrasena.setForeground(new java.awt.Color(0, 0, 0));
        txt_contrasena.setText("CONTRASEÑA");
        fondo_blanco.add(txt_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));
        fondo_blanco.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 310, 10));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        fondo_blanco.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        panel_ingresar.setBackground(new java.awt.Color(240, 0, 11));
        panel_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txt_ingresar.setBackground(new java.awt.Color(255, 255, 255));
        txt_ingresar.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        txt_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        txt_ingresar.setText("INGRESAR");

        javax.swing.GroupLayout panel_ingresarLayout = new javax.swing.GroupLayout(panel_ingresar);
        panel_ingresar.setLayout(panel_ingresarLayout);
        panel_ingresarLayout.setHorizontalGroup(
            panel_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ingresarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txt_ingresar)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panel_ingresarLayout.setVerticalGroup(
            panel_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ingresarLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(txt_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fondo_blanco.add(panel_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 90, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 0, 11));
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 40));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 746, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fondo_blanco.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo_blanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo_blanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombredeusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombredeusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombredeusuarioActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondo_blanco;
    private javax.swing.JLabel img_vote;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panel_ingresar;
    private javax.swing.JLabel text_iniciarsesion;
    private javax.swing.JLabel txt_contrasena;
    private javax.swing.JLabel txt_ingresar;
    private javax.swing.JTextField txt_nombredeusuario;
    private javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
