package login_sistema;

import SistemaContarVotos.Eleccion;
import SistemaContarVotos.GestionActas;
import SistemaContarVotos.GestionCandidatos;
import SistemaContarVotos.GestionElecciones;
import SistemaContarVotos.GestionMesas;
import javax.swing.JPanel;
import vistaContent.ActasElectorales;
import vistaContent.Candidatos;
import vistaContent.ConteoVotos;
import vistaContent.Elecciones;
import vistaContent.Informes;
import vistaContent.MesasElectorales;
import vistaContent.MiembrosMesa;
import vistaContent.Partidos;

/**
 *
 * @author ASUS
 */
public class Principal extends javax.swing.JFrame {

    private GestionCandidatos gestorCandidatos = new GestionCandidatos(100);
    private GestionElecciones gestorElecciones = new GestionElecciones(100);
    private Eleccion[] eleccionesDisponibles;
    private GestionMesas gestorMesas = new GestionMesas(100);
    private GestionActas gestorActas = new GestionActas(100);

    /**
     * Creates new form GestPartidosPoliticos
     */
    public Principal() {
        initComponents();
    }

    private void ShowJPanel(JPanel p) {
        p.setSize(750, 430);
        p.setLocation(0, 0);

        content.removeAll();
        content.add(p);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentprincipal = new javax.swing.JPanel();
        Panelmenu = new javax.swing.JPanel();
        btnPartidos = new javax.swing.JButton();
        btnCandidatos = new javax.swing.JButton();
        btnElecciones = new javax.swing.JButton();
        btnMesasElectorales = new javax.swing.JButton();
        btnMiembrosMesa1 = new javax.swing.JButton();
        btnActasElectorales = new javax.swing.JButton();
        btnConteoVotos = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Panelhead = new javax.swing.JPanel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        contentprincipal.setBackground(new java.awt.Color(255, 255, 255));
        contentprincipal.setForeground(new java.awt.Color(255, 255, 255));
        contentprincipal.setAlignmentX(0.0F);
        contentprincipal.setAlignmentY(0.0F);
        contentprincipal.setPreferredSize(new java.awt.Dimension(800, 500));

        Panelmenu.setBackground(new java.awt.Color(204, 0, 51));
        Panelmenu.setForeground(new java.awt.Color(255, 51, 51));
        Panelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPartidos.setBackground(new java.awt.Color(175, 0, 51));
        btnPartidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPartidos.setForeground(new java.awt.Color(255, 255, 255));
        btnPartidos.setText("Partidos");
        btnPartidos.setBorder(null);
        btnPartidos.setBorderPainted(false);
        btnPartidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPartidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartidosActionPerformed(evt);
            }
        });
        Panelmenu.add(btnPartidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 244, 39));

        btnCandidatos.setBackground(new java.awt.Color(175, 0, 51));
        btnCandidatos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCandidatos.setForeground(new java.awt.Color(255, 255, 255));
        btnCandidatos.setText("Candidatos");
        btnCandidatos.setBorder(null);
        btnCandidatos.setBorderPainted(false);
        btnCandidatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCandidatos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCandidatosActionPerformed(evt);
            }
        });
        Panelmenu.add(btnCandidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 244, 39));

        btnElecciones.setBackground(new java.awt.Color(175, 0, 51));
        btnElecciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnElecciones.setForeground(new java.awt.Color(255, 255, 255));
        btnElecciones.setText("Elecciones");
        btnElecciones.setBorder(null);
        btnElecciones.setBorderPainted(false);
        btnElecciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnElecciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnElecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleccionesActionPerformed(evt);
            }
        });
        Panelmenu.add(btnElecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 244, 39));

        btnMesasElectorales.setBackground(new java.awt.Color(175, 0, 51));
        btnMesasElectorales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMesasElectorales.setForeground(new java.awt.Color(255, 255, 255));
        btnMesasElectorales.setText("Mesas Electorales");
        btnMesasElectorales.setBorder(null);
        btnMesasElectorales.setBorderPainted(false);
        btnMesasElectorales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMesasElectorales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMesasElectorales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesasElectoralesActionPerformed(evt);
            }
        });
        Panelmenu.add(btnMesasElectorales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 244, 39));

        btnMiembrosMesa1.setBackground(new java.awt.Color(175, 0, 51));
        btnMiembrosMesa1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMiembrosMesa1.setForeground(new java.awt.Color(255, 255, 255));
        btnMiembrosMesa1.setText("Miembros de Mesa");
        btnMiembrosMesa1.setBorder(null);
        btnMiembrosMesa1.setBorderPainted(false);
        btnMiembrosMesa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMiembrosMesa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMiembrosMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiembrosMesa1ActionPerformed(evt);
            }
        });
        Panelmenu.add(btnMiembrosMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 244, 39));

        btnActasElectorales.setBackground(new java.awt.Color(175, 0, 51));
        btnActasElectorales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActasElectorales.setForeground(new java.awt.Color(255, 255, 255));
        btnActasElectorales.setText("Actas Electorales");
        btnActasElectorales.setBorder(null);
        btnActasElectorales.setBorderPainted(false);
        btnActasElectorales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActasElectorales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActasElectorales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActasElectoralesActionPerformed(evt);
            }
        });
        Panelmenu.add(btnActasElectorales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 244, 39));

        btnConteoVotos.setBackground(new java.awt.Color(175, 0, 51));
        btnConteoVotos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConteoVotos.setForeground(new java.awt.Color(255, 255, 255));
        btnConteoVotos.setText("Conteo de Votos");
        btnConteoVotos.setBorder(null);
        btnConteoVotos.setBorderPainted(false);
        btnConteoVotos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConteoVotos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConteoVotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConteoVotosActionPerformed(evt);
            }
        });
        Panelmenu.add(btnConteoVotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 244, 39));

        btnInformes.setBackground(new java.awt.Color(175, 0, 51));
        btnInformes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInformes.setForeground(new java.awt.Color(255, 255, 255));
        btnInformes.setText("Informes");
        btnInformes.setBorder(null);
        btnInformes.setBorderPainted(false);
        btnInformes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInformes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformesActionPerformed(evt);
            }
        });
        Panelmenu.add(btnInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 244, 39));

        btnSalir.setBackground(new java.awt.Color(175, 0, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        Panelmenu.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 244, 39));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" OPERACIONES ELECTORALES");
        jLabel1.setToolTipText("");
        jLabel1.setIconTextGap(10);
        Panelmenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 102, 153));
        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GESTION");
        Panelmenu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Panelhead.setBackground(new java.awt.Color(0, 102, 153));
        Panelhead.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout PanelheadLayout = new javax.swing.GroupLayout(Panelhead);
        Panelhead.setLayout(PanelheadLayout);
        PanelheadLayout.setHorizontalGroup(
            PanelheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelheadLayout.setVerticalGroup(
            PanelheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setForeground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(591, 349));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contentprincipalLayout = new javax.swing.GroupLayout(contentprincipal);
        contentprincipal.setLayout(contentprincipalLayout);
        contentprincipalLayout.setHorizontalGroup(
            contentprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentprincipalLayout.createSequentialGroup()
                .addComponent(Panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(contentprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panelhead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentprincipalLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))))
        );
        contentprincipalLayout.setVerticalGroup(
            contentprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(contentprincipalLayout.createSequentialGroup()
                .addComponent(Panelhead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartidosActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new Partidos());
    }//GEN-LAST:event_btnPartidosActionPerformed

    private void btnCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCandidatosActionPerformed
        // TODO add your handling code here:
        Candidatos panelCandidatos = new Candidatos(gestorCandidatos);
        ShowJPanel(panelCandidatos);
    }//GEN-LAST:event_btnCandidatosActionPerformed

    private void btnEleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleccionesActionPerformed
        // TODO add your handling code here:
        Elecciones panel = new Elecciones(gestorCandidatos, gestorElecciones);
        ShowJPanel(panel);
    }//GEN-LAST:event_btnEleccionesActionPerformed

    private void btnMesasElectoralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesasElectoralesActionPerformed
        // TODO add your handling code here:
        MesasElectorales panelmesas = new MesasElectorales(gestorMesas, gestorElecciones);
        ShowJPanel(panelmesas);
    }//GEN-LAST:event_btnMesasElectoralesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMiembrosMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiembrosMesa1ActionPerformed
        // TODO add your handling code here:
        MiembrosMesa panelMiembros = new MiembrosMesa(gestorMesas);
        ShowJPanel(panelMiembros);
    }//GEN-LAST:event_btnMiembrosMesa1ActionPerformed

    private void btnActasElectoralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActasElectoralesActionPerformed

        ActasElectorales actapanel = new ActasElectorales(gestorMesas, gestorActas);
        ShowJPanel(actapanel);
    }//GEN-LAST:event_btnActasElectoralesActionPerformed

    private void btnConteoVotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConteoVotosActionPerformed

        ConteoVotos conteoPanel = new ConteoVotos(gestorActas);
        ShowJPanel(conteoPanel);
    }//GEN-LAST:event_btnConteoVotosActionPerformed

    private void btnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformesActionPerformed
        // TODO add your handling code here:
       Informes informePanel = new Informes(gestorActas);
        ShowJPanel(informePanel);

    }//GEN-LAST:event_btnInformesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panelhead;
    private javax.swing.JPanel Panelmenu;
    private javax.swing.JButton btnActasElectorales;
    private javax.swing.JButton btnCandidatos;
    private javax.swing.JButton btnConteoVotos;
    private javax.swing.JButton btnElecciones;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnMesasElectorales;
    private javax.swing.JButton btnMiembrosMesa1;
    private javax.swing.JButton btnPartidos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel content;
    private javax.swing.JPanel contentprincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
